# Generated by Django 4.2.5 on 2023-09-21 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilisateurs',
            options={},
        ),
        migrations.AlterModelTable(
            name='utilisateurs',
            table='Utilisateurs',
        ),
    ]
