# Generated by Django 4.2.5 on 2023-09-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_alter_utilisateurs_options_alter_utilisateurs_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateurs',
            name='needs_activation',
            field=models.BooleanField(default=False),
        ),
    ]
