# Generated by Django 4.2.5 on 2023-09-20 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='utilisateur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medecinspatients',
            name='medecin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.medecins'),
        ),
        migrations.AddField(
            model_name='medecinspatients',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patients'),
        ),
        migrations.AddField(
            model_name='medecins',
            name='utilisateur_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formulairesante',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patients'),
        ),
        migrations.AddField(
            model_name='formulaireevalstress',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.patients'),
        ),
    ]
