# Generated by Django 4.2.5 on 2023-10-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaireevalstress',
            name='donnees_formulaire',
        ),
    ]
