# Generated by Django 4.2.5 on 2023-11-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairesante',
            name='poids',
            field=models.FloatField(default=float("nan")),
        ),
    ]
