# Generated by Django 4.2.5 on 2023-09-21 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMédecin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='médecins', to=settings.AUTH_USER_MODEL)),
                ('médecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MédecinPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('médecin', models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='medecins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='medecinspatients',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='medecinspatients',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='medecin',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='utilisateur_id',
        ),
        migrations.AlterField(
            model_name='formulaireevalstress',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires_eval_stress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formulairesante',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formulaires_santé', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Medecins',
        ),
        migrations.DeleteModel(
            name='MedecinsPatients',
        ),
        migrations.DeleteModel(
            name='Patients',
        ),
    ]
