# Generated by Django 4.2.5 on 2023-11-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_formulairesante_poids'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaireevalstress',
            name='is_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formulairesante',
            name='is_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formulairesante',
            name='poids',
            field=models.FloatField(default=float("nan")),
        ),
    ]
