# Generated by Django 4.2.5 on 2023-10-19 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0002_remove_formulaireevalstress_donnees_formulaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecinpatient',
            name='patient',
            field=models.ManyToManyField(limit_choices_to={'role': 'patient'}, related_name='medecins', to=settings.AUTH_USER_MODEL),
        ),
    ]
