# Generated by Django 4.2.5 on 2023-10-19 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_medecinpatient_patient'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medecinpatient',
            table='MedecinPatient',
        ),
    ]
