# Generated by Django 4.2.5 on 2023-09-21 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_adminmédecin_médecinpatient_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adminmédecin',
            table='AdminMédecin',
        ),
        migrations.AlterModelTable(
            name='formulaireevalstress',
            table='FormulaireEvalStress',
        ),
        migrations.AlterModelTable(
            name='formulairesante',
            table='FormulaireSante',
        ),
        migrations.AlterModelTable(
            name='médecinpatient',
            table='MédecinPatient',
        ),
    ]
