# Generated by Django 4.2.5 on 2023-09-22 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0004_alter_adminmédecin_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminCompte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_admin', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(limit_choices_to={'role__in': ['admin', 'medecin', 'patient']}, related_name='admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AdminCompte',
            },
        ),
        migrations.DeleteModel(
            name='AdminMédecin',
        ),
    ]
