# Generated by Django 4.2.5 on 2023-09-23 13:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0005_admincompte_delete_adminmédecin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MédecinPatient',
            new_name='MedecinPatient',
        ),
        migrations.AlterModelTable(
            name='medecinpatient',
            table='MedecinPatient',
        ),
    ]
