# Generated by Django 4.2.5 on 2023-09-23 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0006_rename_médecinpatient_medecinpatient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecinpatient',
            name='médecin',
        ),
        migrations.AddField(
            model_name='medecinpatient',
            name='medecin',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='medecin_patients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='medecinpatient',
            name='patient',
            field=models.ForeignKey(default=None, limit_choices_to={'role': 'patient'}, on_delete=django.db.models.deletion.CASCADE, related_name='patients_medecin', to=settings.AUTH_USER_MODEL),
        ),
    ]
