# Generated by Django 4.2.5 on 2023-09-23 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0007_remove_medecinpatient_médecin_medecinpatient_medecin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medecinpatient',
            name='medecin',
            field=models.ForeignKey(limit_choices_to={'role': 'medecin'}, on_delete=django.db.models.deletion.CASCADE, related_name='comptes_medecin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='medecinpatient',
            name='patient',
        ),
        migrations.AddField(
            model_name='medecinpatient',
            name='patient',
            field=models.ManyToManyField(limit_choices_to={'role': 'patient'}, related_name='patients_medecin', to=settings.AUTH_USER_MODEL),
        ),
    ]
