# Generated by Django 4.2.5 on 2023-09-23 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_medecinpatient_medecin_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='medecinpatient',
            table='MedecinCompte',
        ),
    ]
