# Generated by Django 4.2.5 on 2023-10-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_formulairesante_frequence_cardiaque_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulairesante',
            name='tour_de_taille_cm',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
